### ISSUE TITLE
Provide complete Docker image for ease of use

### ISSUE THREAD

**Issue by bootstraponline** [appium/tutorial#11]
The tutorial code and dependencies could be deployed via [Docker](https://github.com/ksoichiro/android-tests/tree/master/docker-emulator) to enable testing on Android. Currently many people are unable to successfully setup an Android development environment for use with appium.

**Comment by davidbaena** [comment]
I can contribute with another appium docker image:
https://registry.hub.docker.com/u/davidbaena/appium

You could set up several appium servers giving bootports, ports and Device as a parameters at start time:

```
$ docker run -d --privileged -v /dev/bus/usb:/dev/bus/usb -e appium_args="-p 4723 -bp 2251 -U 32456"  -p 4723:4723 davidbaena/appium

$ docker run -d --privileged -v /dev/bus/usb:/dev/bus/usb -e appium_args="-p 4724 -bp 2252 -U 43364" -p 4724:4724 davidbaena/appium
```
This image is updated with the latest appium version.

**Comment by bootstraponline** [comment]
awesome! maybe we need an appium docker repo so people can find these images easily.

**Comment by Jonahss** [comment]
Thats not a bad idea. We can link to it in the docs.

**Comment by bootstraponline** [comment]
:+1:

**Comment by vbanthia** [comment]
I have written a tutorial on this,
 https://github.com/vbanthia/appium-docker-test

It will great to get some feedback :)

**Comment by aldeano19** [comment]
@aluedeke or anyone that can answer my question: Given that I have never used Appium before, I have a WhatsApp.java test file, I have a running container of the image you created (aluedeke/appium-android), and I have an Android device pluged into the computer. How do I run that test on that container?. Im using Ubuntu.
