### ISSUE TITLE
Fix broken links

### ISSUE THREAD

**Issue by bootstraponline** [appium/tutorial#13]
UICatalog shuffling has broken some of the tutorial links.
- https://discuss.appium.io/t/appium-setup-for-ios-prebuilt-sample-app-issue-uicatalog-app-zip-need-to-be-updated/408

**Comment by xsmaster** [comment]
Links are broken on the projects main page

**Comment by LouiseReilly** [comment]
Links are still broken in the Android tutorial.

**Comment by azizur** [comment]
There are links broken for iOS tutorial as well.
