### ISSUE TITLE
Running `rake android[test]` fails

### ISSUE THREAD

**Issue by jraczak** [appium/tutorial#21]
Finished in 30 secs

1) Error:
spec home, accessibility, and animation#test_0001_spec:
Timeout::Error: execution expired
/Library/Ruby/Gems/2.0.0/gems/appium_lib-3.0.2/lib/appium_lib/common/helper.rb:43:in sleep' /Library/Ruby/Gems/2.0.0/gems/appium_lib-3.0.2/lib/appium_lib/common/helper.rb:43:inrescue in block in wait'
/Library/Ruby/Gems/2.0.0/gems/appium_lib-3.0.2/lib/appium_lib/common/helper.rb:38:in block in wait' /Library/Ruby/Gems/2.0.0/gems/appium_lib-3.0.2/lib/appium_lib/common/helper.rb:36:inwait'
/Library/Ruby/Gems/2.0.0/gems/appium_lib-3.0.2/lib/appium_lib/driver.rb:161:in rescue in block (3 levels) in promote_singleton_appium_methods' /Library/Ruby/Gems/2.0.0/gems/appium_lib-3.0.2/lib/appium_lib/driver.rb:158:inblock (3 levels) in promote_singleton_appium_methods'
/usr/local/lib/node_modules/appium/appium/submodules/ApiDemos/tutorial/projects/ruby_android/appium/android/pages/home.rb:32:in assert' /usr/local/lib/node_modules/appium/appium/submodules/ApiDemos/tutorial/projects/ruby_android/appium/android/pages/home.rb:9:inaccessibility_click'
/usr/local/lib/node_modules/appium/appium/submodules/ApiDemos/tutorial/projects/ruby_android/appium/android/specs/test.rb:6:in `block (2 levels) in '

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
delete

Understand this is a failure to locate the element. This is built from the tutorial. What needs to be updated?

**Comment by JaniJegoroff** [comment]
@jraczak Have a look at referenced PR that fixes Ruby tests.

**Comment by bootstraponline** [comment]
Does `bundle exec rake android[test]` fail?

**Comment by JaniJegoroff** [comment]
Yes, `bundle exec rake android[test]` will also fail.

**Comment by bootstraponline** [comment]
fixed by https://github.com/appium/tutorial/issues/22

**Comment by jraczak** [comment]
This works beautifully now. Thanks so much @JaniJegoroff for pushing this through so fast and @bootstraponline for the quick merge.

**Comment by JaniJegoroff** [comment]
@jraczak Awesome, happy testing! :)
